---
- name: install redis
  ansible.builtin.dnf:
    name: redis
    state: present

- name: allow remote connections
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '^bind 127\.0\.0\.1 -::1'
    replace: 'bind 0.0.0.0'

- name: start and enable redis
  ansible.builtin.service:
    name: redis
    state: started
    enabled: yes
